name: gazebo-walking-0.3mps
on: [push]

jobs:
  run_controller:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout walking controller repo
      uses: actions/checkout@v2
    - run: time docker build -t loukordos/walking-controller:develop-ubuntu -f Dockerfile.ubuntu .
    - run: cd /home/runner/work/
    - name: Checkout biped sim repo
      uses: actions/checkout@master
      with:
        repository: LouKordos/simplified_biped
        ref: refs/heads/develop
    - run: time docker build -f Dockerfile.ubuntu-plugin -t loukordos/biped-sim:develop-ubuntu .
    - run: mkdir /home/runner/work/plot_data
    - run: docker run -v /home/runner/work/plot_data/:/plot_data -d --net=host -e "RTF=0.1" --name biped-sim loukordos/biped-sim:develop-ubuntu
    - run: docker run -v /home/runner/work/plot_data:/plot_data -e "RTF=0.1" -e "TERM=xterm-256color" -e "SKIP_PINNING=" -e "DISABLE_WEB_UI=" -e "RUNTIME_LIMIT=30" --net=host --name controller loukordos/walking-controller:develop-ubuntu
    - run: docker kill $(docker ps --quiet)
    - name: Upload controller and gazebo logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: /home/runner/work/plot_data/*