name: Stable stepping in place for 30s in Gazebo Bullet
on: [push]

jobs:
  run_controller:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout walking controller repo
      uses: actions/checkout@v2
    - run: time docker build -t loukordos/walking-controller:develop-ubuntu -f Dockerfile.ubuntu .
    - run: cd /home/runner/work/
    - name: Checkout biped sim repo
      uses: actions/checkout@master
      with:
        repository: LouKordos/simplified_biped
        ref: refs/heads/develop
    - run: time docker build -f Dockerfile.ubuntu-plugin -t loukordos/biped-sim:develop-ubuntu .
    - run: mkdir /home/runner/work/plot_data
    - run: docker run -v /home/runner/work/plot_data:/plot_data -d -e "RTF=0.3" -e "TERM=xterm-256color" -e "SKIP_PINNING=" -e "DISABLE_WEB_UI=" -e "RUNTIME_LIMIT=3" --net=host --name controller loukordos/walking-controller:develop-ubuntu
    - run: docker run -v /home/runner/work/plot_data/:/plot_data -d --net=host -e "RTF=0.3" --name biped-sim loukordos/biped-sim:develop-ubuntu
    - run: while [ "$(docker ps --quiet | wc -l)" -eq "2" ]; do sleep 0.5; done && docker stop $(docker ps --quiet)
    - name: Upload controller and gazebo logs
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: /home/runner/work/plot_data/*
    - run: cd /home/runner/work/walking_controller/walking_controller/utils
    - run: python -m pip install -r ../requirements.txt
    - run: python check_energy_used.py 0 10000
    - run: python check_torso_height.py 0.9 1.1
    - run: python check_torso_pos_x.py -0.1 0.1
    - run: python check_torso_pos_y.py -0.1 0.1